version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_testes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_testes
    ports:
      - "3306:3306"  # MySQL continua na porta padrão (3306)
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_testes
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db  # Conecta ao container do MySQL
      PMA_PORT: 3306
    ports:
      - "9090:80"  # phpMyAdmin agora na porta 9090 (mapeia 80 do container para 9090 no host)
    restart: unless-stopped

volumes:
  mysql_data: